#!/bin/bash
################################################
#   BASH : RUNTESTS
#                                                                   #
#       last modified:  2014/07/11                                  #
#       first wrote:    2014/06/17                                  #
#                                                                   #
#       wono (wonho lim: wono@live.com)                             #
#                                                                   #
#####################################################################

# $1: Module name to test. Currently available modules are:
#       - hero
#       - error_handlers
#       - items
#       - maps
#       - monstesrs
#       - skills

COMPILE_FLAG="-sourcepath ../src/ -d ../bin/"
PATH_TO_LOGS="../tests/logs/"

function COMPILE ()
{
    javac ${1}.java $COMPILE_FLAG
}

function RUN ()
{
    cd ../bin/ &&\
    java $1 > ${PATH_TO_LOGS}${1}.log 2>${PATH_TO_LOGS}${1}.err &&\
    cd ../tests
}

function CLEAN ()
{
    rm -rf ../bin/*
}

function RUN_TEST ()
{
    COMPILE $1 && RUN $1 && CLEAN
}

case ${1} in
    hero            )   RUN_TEST TestHero           ;;

    error_handlers  )   RUN_TEST TestErrorHandlers  ;;
    
    items           )   RUN_TEST DemoItems          ;;
    
    maps            )   RUN_TEST DemoMaps           ;;
    
    monsters        )   RUN_TEST TestMonsters       ;;
    
    skills          )   RUN_TEST DemoSkills         ;;
                        
    *)  echo $1 is invalid module name for testing. ;;
esac
