#!/bin/bash
#author Wonho Lim

# $1: Module name to test. Currently available modules are:
#       - command
#       - hero
#       - error_handlers
#       - items
#       - listdr
#       - maps
#       - monstesrs
#       - skills
#       - uinput

COMPILE_FLAG="-sourcepath ../src/ -d ../bin/"
PATH_TO_LOGS="../tests/logs/"

function COMPILE ()
{
    javac ${1}.java $COMPILE_FLAG
}

# with log
function RUN1()
{
    cd ../bin/ &&\
    java $1 > ${PATH_TO_LOGS}${1}.log 2>${PATH_TO_LOGS}${1}.err &&\
    cd ../tests
}

# without log
function RUN2()
{
    cd ../bin/ && java $1 && cd ../tests
}

function CLEAN ()
{
    rm -rf ../bin/*
}

# with run type 1
function RUN_TEST1()
{
    COMPILE $1 && RUN1 $1 && CLEAN
}

# with run type 2
function RUN_TEST2()
{
    COMPILE $1 && RUN2 $1 && CLEAN
}

case ${1} in
    command         )   RUN_TEST2 TestCommand       ;;
    
    hero            )   RUN_TEST1 TestHero          ;;

    error_handlers  )   RUN_TEST1 TestErrorHandlers ;;
    
    items           )   RUN_TEST1 DemoItems         ;;
    
    listdr          )   RUN_TEST2 TestListDr        ;;
    
    maps            )   RUN_TEST1 DemoMaps          ;;
    
    monsters        )   RUN_TEST1 TestMonsters      ;;
    
    skills          )   RUN_TEST1 DemoSkills        ;;
    
    uinput          )   RUN_TEST2 TestUInput        ;;
                        
    *)  echo $1 is invalid module name for testing. ;;
esac
