################################################
#   MAKEFILE:
#       LOS - Monsters module testing program                       #
#                                                                   #
#       last modified:  2014/06/09                                  #
#       first wrote:    2014/06/09                                  #
#                                                                   #
#       wono (wonho lim: wono@live.com)                             #
#                                                                   #
#####################################################################

all:
	make compile && make run && make clean

compile:
	javac tests/*.java
	
run:
	java tests.TestMonsters

clean:
	rm tests/*.class

